openapi: 3.0.0
info:
  version: 1.0.0
  title: Dwarly API Documentation
  description: Dwarly API Documentation
  contact:
    email: mohamed.sheriif.elsayed@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
servers:
  - url: http://localhost:3000/v1
#  - url: https://dev-fixo-api.treesal.com/v1
paths:
  $ref: ./paths/index.yaml
components:
  $ref: ./components/index.yaml
  securitySchemes:
    bearerAuth: # arbitrary name for the security scheme
      type: http
      scheme: bearer
      bearerFormat: JWT # optional, arbitrary value for documentation purposes
